import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Header from "./Components/Header";

const inter = Open_Sans({
  subsets: ["latin"],
  weight: ["700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConvexClientProvider>
      <body className={`min-h-full  bg-[#7945FF] text-white   ${inter.className}`}>
        
          <Header/>
          <div className="max-w-[800px]  mx-auto">
            {children}
          </div>
        </body>
          </ConvexClientProvider> 
    </html>
  );
}
