import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lilita_One } from "next/font/google";
import { Nerko_One } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Header from "./Components/Header";

const inter = Lilita_One({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConvexClientProvider>
      <body className={`min-h-full text-black   ${inter.className}`}>
        
          <Header/>
          <div className="max-w-[800px] mx-auto">
            {children}
          </div>
        </body>
          </ConvexClientProvider> 
    </html>
  );
}
